import { Router } from 'express';
import * as Table from '../controllers/table.controller';
import { requireAuth, requireRole } from '../middleware/auth';
import { operatorReadLimiter, operatorWriteLimiter } from '../middleware/rateLimiter';
import { requireVenueFeature } from '../middleware/venueFeature';
const router = Router();
router.get  ('/',                  requireAuth, requireVenueFeature('staffConsole'), operatorReadLimiter, Table.getTables);
router.post ('/',                  requireAuth, requireRole('OWNER','MANAGER'), requireVenueFeature('staffConsole'), operatorWriteLimiter, Table.createTable);
router.get  ('/events/recent',     requireAuth, requireVenueFeature('staffConsole'), operatorReadLimiter, Table.getRecentTableEvents);
router.patch('/:tableId/status',   requireAuth, requireVenueFeature('staffConsole'), operatorWriteLimiter, Table.updateTableStatus);
router.get  ('/:tableId/events',   requireAuth, requireVenueFeature('staffConsole'), operatorReadLimiter, Table.getTableEvents);
router.post ('/reset-all',         requireAuth, requireRole('OWNER','MANAGER'), requireVenueFeature('staffConsole'), operatorWriteLimiter, Table.resetAllTables);
export default router;
